import React from "react";
import {
  X,
  Calendar,
  Clock,
  Building,
  Sprout,
  AlertTriangle,
  CheckCircle2,
  Zap,
  Bot,
  UserCheck,
  Tag,
  Key,
  Info,
} from "lucide-react";

const TaskDetailsModal = ({ task, isOpen, onClose, onEdit, onStatusChange }) => {
  if (!isOpen || !task) return null;

  const getSourceLabel = (src) => {
    if (src === "automation") {
      return {
        text: "Generated by Farmio Automation",
        icon: Zap,
        badgeClass: "badge-automation",
      };
    }
    if (src === "ai") {
      return {
        text: "Generated by Farmio Demo AI",
        icon: Bot,
        badgeClass: "badge-ai",
      };
    }
    return {
      text: "Created manually",
      icon: UserCheck,
      badgeClass: "badge-manual",
    };
  };

  const sourceInfo = getSourceLabel(task.source);
  const SourceIcon = sourceInfo.icon;

  const due = task.dueAt ? new Date(task.dueAt) : null;
  const created = task.createdAt ? new Date(task.createdAt) : null;
  const completed = task.completedAt ? new Date(task.completedAt) : null;
  const now = new Date();
  const isOverdue =
    due && due < now && (task.status === "pending" || task.status === "in_progress");

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content task-details-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="header-title-box">
            <span className="task-type-badge-lg">
              {task.type === "irrigation" && "💧"}
              {task.type === "fertilizer" && "🧪"}
              {task.type === "pest" && "🐛"}
              {task.type === "disease" && "🦠"}
              {task.type === "harvest" && "🌾"}
              {task.type === "planting" && "🌱"}
              {task.type === "inspection" && "🔍"}
              {task.type === "weather" && "🌦️"}
              {task.type === "market" && "📈"}
              {task.type === "general" && "📋"}
              <span className="capitalize">{task.type} Task</span>
            </span>
            <h3>{task.title}</h3>
          </div>
          <button type="button" className="close-btn" onClick={onClose}>
            <X size={20} />
          </button>
        </div>

        <div className="task-details-body">
          <div className="details-source-banner">
            <SourceIcon className="source-banner-icon" />
            <span>{sourceInfo.text}</span>
          </div>

          <div className="details-grid">
            <div className="detail-item">
              <span className="detail-label">Status</span>
              <span className={`status-pill status-${task.status}`}>
                {task.status === "completed" && "✓ Completed"}
                {task.status === "in_progress" && "⚙ In Progress"}
                {task.status === "pending" && (isOverdue ? "⚠️ Overdue" : "⏳ Pending")}
                {task.status === "cancelled" && "🚫 Cancelled"}
              </span>
            </div>

            <div className="detail-item">
              <span className="detail-label">Priority</span>
              <span className={`priority-tag prio-${task.priority}`}>
                {task.priority?.toUpperCase()}
              </span>
            </div>

            <div className="detail-item">
              <span className="detail-label">Farm</span>
              <div className="detail-value-with-icon">
                <Building size={16} />
                <span>{task.farm?.name || "Farm"}</span>
              </div>
            </div>

            <div className="detail-item">
              <span className="detail-label">Crop</span>
              <div className="detail-value-with-icon">
                <Sprout size={16} />
                <span>{task.crop?.name || "General Farm Task"}</span>
              </div>
            </div>

            <div className="detail-item">
              <span className="detail-label">Due Date</span>
              <div className="detail-value-with-icon">
                <Calendar size={16} />
                <span className={isOverdue ? "danger-text bold" : ""}>
                  {due ? due.toLocaleString() : "None"}
                </span>
              </div>
            </div>

            <div className="detail-item">
              <span className="detail-label">Created At</span>
              <div className="detail-value-with-icon">
                <Clock size={16} />
                <span>{created ? created.toLocaleString() : "Unknown"}</span>
              </div>
            </div>

            {completed && (
              <div className="detail-item">
                <span className="detail-label">Completed At</span>
                <div className="detail-value-with-icon">
                  <CheckCircle2 size={16} className="text-success" />
                  <span>{completed.toLocaleString()}</span>
                </div>
              </div>
            )}

            {task.automationKey && (
              <div className="detail-item">
                <span className="detail-label">Automation Key</span>
                <div className="detail-value-with-icon">
                  <Key size={16} />
                  <code>{task.automationKey}</code>
                </div>
              </div>
            )}
          </div>

          {task.description && (
            <div className="details-section">
              <h4>Description</h4>
              <p className="details-text-box">{task.description}</p>
            </div>
          )}

          {task.reason && (
            <div className="details-section">
              <h4>Reason / Trigger</h4>
              <p className="details-text-box reason-box">{task.reason}</p>
            </div>
          )}
        </div>

        <div className="modal-footer">
          {task.status !== "completed" ? (
            <button
              type="button"
              className="btn-success"
              onClick={() => {
                onStatusChange(task._id, "completed");
                onClose();
              }}
            >
              ✓ Mark Complete
            </button>
          ) : (
            <button
              type="button"
              className="btn-secondary"
              onClick={() => {
                onStatusChange(task._id, "pending");
                onClose();
              }}
            >
              Reopen Task
            </button>
          )}

          <button
            type="button"
            className="btn-outline-primary"
            onClick={() => {
              onClose();
              onEdit(task);
            }}
          >
            Edit Task
          </button>
        </div>
      </div>
    </div>
  );
};

export default TaskDetailsModal;
